on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      matrix:
        required: false
        type: string
        default: "[]"

concurrency: # only run one instance of workflow at any one time
  group: build-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  VERSION: ${{ inputs.version }}
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  bucket:
    runs-on: ubuntu-latest
    outputs:
      lambda_bucket_name: ${{ steps.get_bucket_name.outputs.bucket_lambda }}
    steps:
      - uses: actions/checkout@v4

      - name: Get lambda code bucket
        id: deploy_bucket
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket
          tg_action: init

      - name: Get bucket name
        id: get_bucket_name
        env:
          TG_OUTPUTS: ${{ steps.deploy_bucket.outputs.tg_outputs  }}
        run: |
          echo "bucket_lambda=$(echo $TG_OUTPUTS | jq -r '.bucket_lambda.value')" >> $GITHUB_OUTPUT

  lambdas:
    needs: bucket
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: "Build ${{ matrix.value }} Lambda"
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        env:
          LAMBDA_NAME: ${{ matrix.value }}
        with:
          just_action: lambda-build

      - name: "Upload ${{ matrix.value }} Lambda"
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        env:
          LAMBDA_NAME: ${{ matrix.value }}
          BUCKET_NAME: ${{ needs.bucket.outputs.lambda_bucket_name }}
          VERSION: ${{ inputs.version }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          just_action: lambda-upload
