on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
    outputs:
      lambda_bucket:
        description: "Bucket containing lambda zips"
        value: ${{ jobs.lambdas.outputs.lambda_bucket_name }}
      lambda_version:
        description: "Valid lambda version"
        value: ${{ inputs.version }}
      lambda_version_files:
        description: "List of lambda version files"
        value: ${{ jobs.lambdas.outputs.lambda_version_files }}

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role"

jobs:
  lambdas:
    runs-on: ubuntu-latest
    outputs:
      lambda_bucket_name: ${{ steps.get_bucket_name.outputs.bucket_lambda }}
      lambda_version_files: ${{ steps.get_build_files.outputs.just_outputs }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}

      - name: Get code bucket outputs
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        id: code_action
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket
          tg_action: init

      - name: Get bucket names
        id: get_bucket_name
        env:
          TG_OUTPUTS: ${{ steps.code_action.outputs.tg_outputs }}
        run: |
          echo "bucket_lambda=$(echo $TG_OUTPUTS | jq -r '.bucket_lambda.value')" >> $GITHUB_OUTPUT

      - name: Check Lambda version exists
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        env:
          BUCKET_NAME: ${{ steps.get_bucket_name.outputs.bucket_lambda }}
          VERSION: ${{ inputs.version }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          just_action: check-version

      - name: Get build files
        id: get_build_files
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        env:
          BUCKET_NAME: ${{ steps.get_bucket_name.outputs.bucket_lambda }}
          VERSION: ${{ inputs.version }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          just_action: get-version-files
