on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      lambda_bucket:
        description: "Bucket containing lambda zips"
        required: true
        type: string
      lambda_version:
        description: "Valid lambda version"
        required: true
        type: string
      matrix:
        required: false
        type: string
        default: "[]"
      lambda_keep:
        description: "Number of lambda versions to keep"
        default: '5'
        type: string


concurrency: # only run one instance of workflow at any one time
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_lambda_version: ${{ inputs.lambda_version }}
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check Lambda version
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        env:
          BUCKET_NAME: ${{ inputs.lambda_bucket }}
          VERSION: ${{ inputs.lambda_version }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          just_action: check-version

  lambdas:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set AppSpec paths
        id: appspec
        shell: bash
        run: |
          lambda_function_name="${{ inputs.environment }}-${{ github.event.repository.name }}-${{ matrix.value }}"
          lambda_zip_key="${{ inputs.lambda_version }}/${{ matrix.value }}.zip"
          lambda_appspec_key="${{ inputs.lambda_version }}/${{ matrix.value }}-appspec.zip"
          echo "lambda_function_name=$lambda_function_name" >> $GITHUB_OUTPUT
          echo "lambda_zip_key=$lambda_zip_key" >> $GITHUB_OUTPUT
          echo "lambda_appspec_key=$lambda_appspec_key" >> $GITHUB_OUTPUT

      - name: Publish new lambda version
        id: publish
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        env:
          BUCKET_NAME: ${{ inputs.lambda_bucket }}
          FUNCTION_NAME: ${{ steps.appspec.outputs.lambda_function_name }}
          LAMBDA_ZIP_KEY: ${{ steps.appspec.outputs.lambda_zip_key }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          just_action: lambda-create-version