name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_lambda_version: this
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      backend_dirs: ${{ steps.backend_dirs.outputs.just_outputs }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/oidc

      - name: Get Backend Directories
        id: backend_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.1.3
        with:
          just_action: backend-get-directories

  lambdas:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.backend_dirs) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}
          tg_action: destroy

  build:
    needs:
      - lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Destroy code
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket
          tg_action: destroy
