name: Dev Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: dev
      version: ${{ github.sha }}

  get:
    needs: build
    uses: ./.github/workflows/get_build.yml
    with:
      environment: dev
      version: ${{ github.sha }}


  # dev:
  #   uses: ./.github/workflows/deploy.yml
  #   needs: get
  #   secrets: inherit
  #   with:
  #     environment: dev
  #     version: ${{ needs.get.outputs. }}
