name: Dev Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: dev
      version: ${{ github.sha }}

  lambdas:
    needs: build
    uses: ./.github/workflows/infra_deploy.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}
      lambda_bucket: ${{ needs.build.outputs.lambda_bucket }}
      lambda_version: ${{ github.sha }}

  dev:
    uses: ./.github/workflows/deploy.yml
    needs: 
      - build
      - lambdas
    with:
      environment: dev
      infra_version: ${{ github.sha }}
      lambda_bucket: ${{ needs.build.outputs.lambda_bucket }}
      lambda_version: ${{ needs.build.outputs.lambda_version }}
