on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be deployed"
        required: true
        type: string
      lambda_bucket:
        description: "Bucket containing lambda zips"
        required: true
        type: string


concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      lambdas_dirs: ${{ steps.lambdas_dirs.outputs.just_outputs }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/oidc

      - name: Get lambdas Directories
        id: lambdas_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.1.3
        with:
          just_action: lambda-get-directories

  lambdas:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.lambdas_dirs) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}

  # consumer:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ inputs.infra_version }}

  #     - name: Deploy consumer infra
  #       id: deploy
  #       uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
  #       with:
  #         aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
  #         tg_directory: infra/live/${{ inputs.environment }}/aws/consumer
