on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be deployed"
        required: true
        type: string
    outputs:
      lambda_bucket:
        description: "Bucket containing lambda zips"
        value: ${{ jobs.bucket.outputs.lambda_bucket_name }}

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_lambda_version: ${{ inputs.lambda_version }}
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  bucket:
    runs-on: ubuntu-latest
    outputs:
      lambda_bucket_name: ${{ steps.get_bucket_name.outputs.bucket_lambda }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy api infra
        id: deploy
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket

      - name: Get bucket name
        id: get_bucket_name
        env:
          TG_OUTPUTS: ${{ steps.code_action.outputs.tg_outputs  }}
        run: |
          echo "bucket_lambda=$(echo $TG_OUTPUTS | jq -r '.bucket_lambda.value')" >> $GITHUB_OUTPUT
